create table if not exists main.stock_data_daily
(
    symbol                text    not null,
    name                  text    not null,
    type                  text    not null,
    interval              text    not null,
    date                  text    not null,
    open                  real    not null,
    high                  real    not null,
    low                   real    not null,
    close                 real    not null,
    adjusted_close        real    not null,
    volume                integer not null,
    avg_volume            real,
    is_swing_high         integer,
    swing_high            real,
    swing_high_cross_up   integer,
    swing_high_cross_down integer,
    is_swing_low          integer,
    swing_low             real,
    swing_low_cross_up    integer,
    swing_low_cross_down  integer,
    rs                    real,
    is_rs_52_week_high    integer,
    atr                   real,
    is_gap_up             integer,
    is_gap_down           integer,
    is_doji_bar           integer,
    is_bull_bar           integer,
    is_bear_bar           integer,
    ema_10                real,
    ema_21                real,
    ema_50                real,
    ema_200               real,
    rsi_14                real,
    is_high_63            integer,
    is_high_252           integer,
    is_low_63             integer,
    is_low_252            integer,
    buy_signal            integer,
    sell_signal           integer,
    signal                integer,
    signal_change         integer,
    primary key (symbol, date)
);

create index main.stock_data_daily_date on stock_data_daily (date);
create index stock_data_daily_symbol_idx on stock_data_daily (symbol);

